### ISSUE TITLE
issue with flutter sdk

### ISSUE THREAD

**Issue by inquisiteur** [passbase/passbase-sdk#1]
I am having isseur with the flutter sdk

<img width="1403" alt="Screen Shot 2020-01-17 at 12 59 46 PM" src="https://user-images.githubusercontent.com/45268000/72636431-0cd7c400-392d-11ea-97a9-3001fc4f9c7e.png">

**Comment by skorostetskyi** [comment]
@inquisiteur our support team has contacted you. Do you have any current issues with Flutter?

**Comment by stephangopaul** [comment]
Hello @skorostetskyi, I am having the same issue when trying to implement the passbase flutter plugin. 
Kindly advise please.
