### ISSUE TITLE
Flutter plugin failed to load module

### ISSUE THREAD

**Issue by stephangopaul** [passbase/passbase-sdk#3]
Hello @skorostetskyi, I am having an issue when trying to implement the Passbase Flutter plugin.
I am getting the below error. 

![98213545-a628a300-1f5e-11eb-8010-9c9a3992fe5b](https://user-images.githubusercontent.com/1753174/98324807-b5fbc200-2006-11eb-9349-6d077dfa5fea.png)

Kindly advise please.

**Comment by skorostetskyi** [comment]
Hello @stephangopaul, I will do my best to help you.
What is your Xcode version?

**Comment by stephangopaul** [comment]
Hello @skorostetskyi, I am on Xcode 11.1 (11A1027)

**Comment by skorostetskyi** [comment]
You have to update your Xcode to v12.x, and it will work.

**Comment by stephangopaul** [comment]
Thank you
